service: serverless-wpp-send-message
frameworkVersion: '3'
custom:
  dotenvVars: ${file(configs.js)}
  # serverless-offline-sqs:
  #   autoCreate: false # create queue if not exists
  #   apiVersion: '2012-11-05'
  #   endpoint: ${self:custom.dotenvVars.SQS_ENDPOINT, 'http://sqs:9324'}
  #   region: us-east-1
  #   accessKeyId: test
  #   secretAccessKey: test
  #   skipCacheInvalidation: false
  serverless-offline:
    httpPort: 4000
  node_env:
    dev: development
    prod: production

provider:
  name: aws
  runtime: nodejs24.x
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedMethods:
        - POST
      allowedHeaders:
        - "*"
  timeout: 30
  memorySize: 128
  deploymentBucket:
    name: ${self:custom.dotenvVars.DEPLOYMENT_BUCKET}
  stage: ${opt:stage, 'prod'}
  environment: ${file(configs.js)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - events:*
        - lambda:*
        - sqs:*
      Resource: '*'

plugins:
  # - serverless-offline-sqs
  - serverless-plugin-scripts
  - serverless-offline

functions:
  api:
    handler: dist/src/main/api.handler
    environment:
      SEND_MESSAGE_QUEUE_URL: !Ref SendMessageQueue
    events:
      - httpApi:
          path: /webhooks/z-api/received/{webhookSecret}
          method: post

  sendMessage:
    handler: dist/src/main/send-message.handler
    reservedConcurrency: 3
    events:
      - sqs:
          arn: !GetAtt SendMessageQueue.Arn
          batchSize: 1
          maximumConcurrency: 3

resources:
  Resources:
    SendMessageDlq:
      Type: AWS::SQS::Queue
      Properties:
        MessageRetentionPeriod: 1209600
    SendMessageQueue:
      Type: AWS::SQS::Queue
      Properties:
        VisibilityTimeout: 180
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt SendMessageDlq.Arn
          maxReceiveCount: 3
