#!/bin/bash
set -e

cat>.env<<EOF
# AWS
DEPLOYMENT_BUCKET=${DEPLOYMENT_BUCKET}
SQS_ENDPOINT=${SQS_ENDPOINT}

# Z-API
Z_API_INSTANCE_ID=${Z_API_INSTANCE_ID}
Z_API_INSTANCE_TOKEN=${Z_API_INSTANCE_TOKEN}
Z_API_SECURITY_TOKEN=${Z_API_SECURITY_TOKEN}
Z_API_BASE_URL=${Z_API_BASE_URL}

# Auth token
AUTH_TOKEN=${AUTH_TOKEN}
EOF
