#!/bin/bash
set -e

cat>.env<<EOF
# AWS
DEPLOYMENT_BUCKET=${DEPLOYMENT_BUCKET}

# Z-API
Z_API_INSTANCE_ID=${Z_API_INSTANCE_ID}
Z_API_INSTANCE_TOKEN=${Z_API_INSTANCE_TOKEN}
Z_API_SECURITY_TOKEN=${Z_API_SECURITY_TOKEN}
Z_API_BASE_URL=${Z_API_BASE_URL}
Z_API_WEBHOOK_SECRET=${Z_API_WEBHOOK_SECRET}
SOURCE_GROUP_ID=${SOURCE_GROUP_ID}
BROADCAST_IDS=${BROADCAST_IDS}
IGNORE_FROM_ME=${IGNORE_FROM_ME}
ALLOWED_PARTICIPANT_PHONES=${ALLOWED_PARTICIPANT_PHONES}
EOF
