const {
  SQS_ENDPOINT,
  Z_API_INSTANCE_ID,
  Z_API_INSTANCE_TOKEN,
  Z_API_SECURITY_TOKEN,
  Z_API_BASE_URL,
  AUTH_TOKEN,
} = process.env

export {
  SQS_ENDPOINT,
  Z_API_INSTANCE_ID,
  Z_API_INSTANCE_TOKEN,
  Z_API_SECURITY_TOKEN,
  Z_API_BASE_URL,
  AUTH_TOKEN,
}
