name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      STAGE: prod
      # AWS Credentials
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      # Service variables
      Z_API_INSTANCE_ID: ${{ secrets.Z_API_INSTANCE_ID }}
      Z_API_INSTANCE_TOKEN: ${{ secrets.Z_API_INSTANCE_TOKEN }}
      Z_API_SECURITY_TOKEN: ${{ secrets.Z_API_SECURITY_TOKEN }}
      Z_API_BASE_URL: ${{ secrets.Z_API_BASE_URL }}
      Z_API_WEBHOOK_SECRET: ${{ secrets.Z_API_WEBHOOK_SECRET }}
      SOURCE_GROUP_ID: ${{ secrets.SOURCE_GROUP_ID }}
      BROADCAST_IDS: ${{ secrets.BROADCAST_IDS }}
      IGNORE_FROM_ME: ${{ secrets.IGNORE_FROM_ME }}
      ALLOWED_PARTICIPANT_PHONES: ${{ secrets.ALLOWED_PARTICIPANT_PHONES }}

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Configure AWS credentials
        run: aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}

      - name: Install
        run: |
          if [ -e package-lock.json ]; then
            npm ci --prefer-offline --no-audit
          else
            npm i
          fi

      - name: Build
        run: |
          npm run build

      - name: BuildEnv
        run: |
          sudo chmod +x config/env.config.sh
          sh config/env.config.sh

      - name: Deploy
        run: |
          npx serverless deploy --stage ${{ env.STAGE }}
